export const STEPS = {
  INITIAL: 'INITIAL',
  COLLECTING_DATE: 'COLLECTING_DATE',
  COLLECTING_TIME: 'COLLECTING_TIME',
  COLLECTING_PARTICIPANTS: 'COLLECTING_PARTICIPANTS',
  CONFIRMATION: 'CONFIRMATION',
} as const;

export type Step = keyof typeof STEPS;